image: node:20.19
stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - echo -e "machine gitlab.com\nlogin gitlab-ci-token\npassword ${GIT_ACCESS_TOKEN}" > ~/.netrc
    - yarn
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "mirror/main"'

build:
  stage: build
  script:
    - yarn generate
  artifacts:
    paths:
      - .output/public
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      variables:
        APP_ENY_URL: $DEV_APP_URL
    - if: '$CI_COMMIT_BRANCH == "main"'
      variables:
        APP_ENY_URL: $PROD_APP_URL
    - if: '$CI_COMMIT_BRANCH == "mirror/main"'
      variables:
        APP_ENY_URL: $PROD_APP_URL

upload_to_s3:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - aws s3 sync .output/public s3://$DEPLOY_TARGET --delete
  dependencies:
    - build
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      variables:
        DEPLOY_TARGET: $DEV_DEPLOY_TARGET
    - if: '$CI_COMMIT_BRANCH == "main"'
      variables:
        DEPLOY_TARGET: $PROD_DEPLOY_TARGET
    - if: '$CI_COMMIT_BRANCH == "mirror/main"'
      variables:
        DEPLOY_TARGET: $PROD_DEPLOY_TARGET

invalidate_cloudfront:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST --paths "/*"
  needs:
    - job: upload_to_s3
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      variables:
        CLOUDFRONT_DIST: $DEV_CDN_ID
    - if: '$CI_COMMIT_BRANCH == "main"'
      variables:
        CLOUDFRONT_DIST: $PROD_CDN_ID
    - if: '$CI_COMMIT_BRANCH == "mirror/main"'
      variables:
        CLOUDFRONT_DIST: $PROD_CDN_ID
